---
name: "RegistrationConfigurationReadStore"
type: "readstore"
version: "1.0.0"
consumes:
  events:
    UnitCreatedEvent:
      name: "UnitCreatedEvent"
      schemaUri: "https://sv.telesv.com/schemas/UnitCreatedEvent_v1.004.json"
    UnitUpdatedEvent:
      name: "UnitUpdatedEvent"
      schemaUri: "https://sv.telesv.com/schemas/UnitUpdatedEvent_v1.004.json"
    LocationAssociationCreatedEvent:
      name: "LocationAssociationCreatedEvent"
      schemaUri: "https://sv.telesv.com/schemas/LocationAssociationCreatedEvent_v1.002.json"
    LocationAssociationUpdatedEvent:
      name: "LocationAssociationUpdatedEvent"
      schemaUri: "https://sv.telesv.com/schemas/LocationAssociationUpdatedEvent_v1.002.json"
    LocationAssociationDeletedEvent:
      name: "LocationAssociationDeletedEvent"
      schemaUri: "https://sv.telesv.com/schemas/LocationAssociationDeletedEvent_v1.002.json"
    BedLocationCreatedEvent:
      name: "BedLocationCreatedEvent"
      schemaUri: "https://sv.telesv.com/schemas/BedLocationCreatedEvent_v2.001.json"
    BedLocationUpdatedEvent:
      name: "BedLocationUpdatedEvent"
      schemaUri: "https://sv.telesv.com/schemas/BedLocationUpdatedEvent_v2.001.json"
